# ----------- CONFIGURABLE START -----------
title:            "The Source code to my twisted internals"
description:      "My online journal/blog"
url:              http://sandeep06011991.github.io # Site url, without a slash at the end.
signoff:          "Sandeep Polisetty" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         Posts
    url:          /blog
    external:     false
  - name:         About me
    external:     false
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"