# ----------- CONFIGURABLE START -----------
title:            "Sandeep Polisetty Journal"
description:      "Sandeep Polisetty online journal/blog"
#url:              http://localhost:4000
url:              http://sandeep06011991.github.io
signoff:          "Sandeep Polisetty" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         Projects
    url:          /projects.html
    external:     false
#  - name:         Posts
#    url:          /blog.html
#    external:     false
  - name:         Papers
    url:          /papers.html
    external:     false

  - name:         About me
    url:          /
    external:     false
  - name:         Fitness
    url:          /fitness.html
    external:     false
  - name:         Cooking
    url:          /cooking.html
    external:      false

  #- name:         CV
  #  url:          /resume-sandeep.pdf
  #  external:     false

# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"

plugins_dir:
  - jekyll-seo-tag

collections:
  papers:
    output: true
    permalink: /papers/:path/
  bodybuilding:
    output:  true
    permalink: /bodybuilding/:path/