# top level stuff you probably don't need to touch
highlighter: rouge
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://sandeep06011991.github.io/
baseurl:
title: Sandeep Polisetty
author: Sandeep Polisetty
description: Personal blog and resume
avatar: physique.png
email: sandeep06011991@gmail.com
github: sandeep06011991 # username

stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: username
google_analytics: UA-69391421-1
email: sandeep06011991@gmail.com


# needed for travis-ci build
exclude: [vendor]
